name = "Wildfires"
uuid = "8a83dac0-8d4f-4b7e-b327-bade5b93bcdd"
version = "0.2.0"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
WildfiresGPUExt = ["Adapt", "KernelAbstractions", "GPUArraysCore"]
WildfiresMakieExt = "Makie"
WildfiresNeuralPDEExt = ["Random", "NeuralPDE", "ModelingToolkit", "DomainSets", "Lux", "Optimization", "OptimizationOptimJL"]
WildfiresPINNExt = ["Random", "Lux", "ComponentArrays", "ForwardDiff", "Zygote", "Optimization", "OptimizationOptimisers"]

[compat]
Adapt = "4.4.0"
ComponentArrays = "0.15.32"
DomainSets = "0.7"
ForwardDiff = "1.3.2"
GPUArraysCore = "0.2"
KernelAbstractions = "0.9.40"
LinearAlgebra = "1.12.0"
Lux = "1.31.3"
Makie = "0.24.6"
ModelingToolkit = "11.11.1"
NeuralPDE = "5.21.0"
Optimization = "5.5.0"
OptimizationOptimJL = "0.4.10"
OptimizationOptimisers = "0.3.16"
Random = "1.11.0"
Zygote = "0.7.10"
julia = "1.12"

[extras]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Adapt", "Random", "Makie", "Lux", "ComponentArrays", "ForwardDiff", "Zygote", "Optimization", "OptimizationOptimisers", "KernelAbstractions", "GPUArraysCore", "NeuralPDE", "ModelingToolkit", "OptimizationOptimJL", "DomainSets"]
