name = "Wildfires"
uuid = "8a83dac0-8d4f-4b7e-b327-bade5b93bcdd"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
GlobalGrids = "04ffc4db-dae8-4dbd-80c0-66bcb7ba3f11"
H3 = "f62fece2-b996-571a-b4c9-e662aba1c617"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Landfire = "16f38fd6-0379-4569-89bb-2d3d56e50de8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MapTiles = "fea52e5a-b371-463b-85f5-81770daa2737"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
OSMGeocoder = "28a637ce-2736-498a-9075-487c6d86a7c1"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
TileProviders = "263fe934-28e1-4ae9-998a-c2629c5fede6"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ArchGDAL = "0.10.10"
CSV = "0.10.15"
ColorTypes = "0.12.1"
DBInterface = "2.6.1"
DataFrames = "1.7.1"
Dates = "1.11.0"
Extents = "0.1.6"
FixedPointNumbers = "0.8.5"
Flux = "0.16.5"
GLMakie = "0.13.6"
GeoFormatTypes = "0.4.4"
GeoInterface = "1.5.0"
GeoJSON = "0.8.4"
GeoMakie = "0.7.15"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.26"
H3 = "0.3.2"
HTTP = "1.10.17"
ImageMagick = "1.4.2"
Interpolations = "0.16.2"
JSON3 = "1.14.3"
Landfire = "0.0.1"
LinearAlgebra = "1.12.0"
Lux = "1.21.1"
Makie = "0.24.6"
MapTiles = "1.0.2"
MethodOfLines = "0.11.9"
ModelingToolkit = "10.26.1"
NaturalEarth = "0.1.0"
OSMGeocoder = "0.0.1"
Observables = "0.5.5"
Optimisers = "0.4.6"
OrdinaryDiffEq = "6.103.0"
PlutoUI = "0.7.71"
ProgressMeter = "1.11.0"
Proj = "1.9.0"
Rasters = "0.14.6"
Reactant = "0.2.177"
SQLite = "1.6.1"
Scratch = "1.3.0"
Statistics = "1.11.1"
StyledStrings = "1.11.0, 1"
Surrogates = "7.0.1"
TileProviders = "0.1.4"
Tyler = "0.2.4"
Zygote = "0.7.10"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
