name = "Wildfires"
uuid = "8a83dac0-8d4f-4b7e-b327-bade5b93bcdd"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
WildfiresPINNExt = ["Lux", "ComponentArrays", "ForwardDiff", "Zygote", "Optimization", "OptimizationOptimisers"]

[compat]
ComponentArrays = "0.15.32"
ForwardDiff = "1.3.2"
LinearAlgebra = "1.12.0"
Lux = "1.31.3"
Makie = "0.24.6"
Optimization = "5.5.0"
OptimizationOptimisers = "0.3.16"
Random = "1.11.0"
Zygote = "0.7.10"
julia = "1.12"

[extras]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Lux", "ComponentArrays", "ForwardDiff", "Zygote", "Optimization", "OptimizationOptimisers"]
