name = "Wildfires"
uuid = "8a83dac0-8d4f-4b7e-b327-bade5b93bcdd"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MapTiles = "fea52e5a-b371-463b-85f5-81770daa2737"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
TileProviders = "263fe934-28e1-4ae9-998a-c2629c5fede6"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"

[compat]
ArchGDAL = "0.10.10"
DataFrames = "1.7.1"
Dates = "1.11.0"
Extents = "0.1.6"
GLMakie = "0.13.6"
GMT = "1.33.0"
GeoInterface = "1.5.0"
GeoJSON = "0.8.4"
GeoMakie = "0.7.15"
GeometryOps = "0.1.26"
HTTP = "1.10.17"
Makie = "0.24.6"
MapTiles = "1.0.2"
NaturalEarth = "0.1.0"
Observables = "0.5.5"
PlutoUI = "0.7.71"
Proj = "1.9.0"
Rasters = "0.14.6"
TileProviders = "0.1.4"
Tyler = "0.2.4"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
